import fs from 'fs/promises';
import path from 'path';
import jsyaml from 'js-yaml';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const dataDir = path.resolve(rootDir, 'data');
const outFile = path.resolve(rootDir, 'data-build.ts');

async function prepareData() {
  try {
    const files = await fs.readdir(dataDir);
    const yamlFiles = files.filter(file => file.endsWith('.yaml') || file.endsWith('.yml'));

    const allData = {};

    for (const file of yamlFiles) {
      const filePath = path.join(dataDir, file);
      const content = await fs.readFile(filePath, 'utf8');
      const data = jsyaml.load(content);
      const key = path.basename(file, path.extname(file));
      allData[key] = data;
    }

    const fileContent = `// This file is auto-generated by scripts/prepare-data.mjs. Do not edit manually.\n\nexport const prebuiltData = ${JSON.stringify(allData, null, 2)};\n`;

    await fs.writeFile(outFile, fileContent, 'utf8');
    console.log(`Successfully generated ${outFile}`);
  } catch (err) {
    console.error('Error preparing data:', err);
    process.exit(1);
  }
}

prepareData();
